// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MvcEshop.Controllers
{
    public partial class ReportController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InitializationBeforeSend()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InitializationBeforeSend);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetCustomersSearchResults()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetCustomersSearchResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddReceiver()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddReceiver);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetSendingConfirmationPartialView()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetSendingConfirmationPartialView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateInvoiceReportByAccountIdInPDF()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateInvoiceReportByAccountIdInPDF);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportController Actions { get { return MVC.Report; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Report";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Report";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string InitializationBeforeSend = "InitializationBeforeSend";
            public readonly string SendReport = "SendReport";
            public readonly string GetCustomersSearchResults = "GetCustomersSearchResults";
            public readonly string AddReceiver = "AddReceiver";
            public readonly string GetSendingConfirmationPartialView = "GetSendingConfirmationPartialView";
            public readonly string CreateExcelReportForCurrentCreditOfAccounts = "CreateExcelReportForCurrentCreditOfAccounts";
            public readonly string CreateInvoiceReportByAccountIdInPDF = "CreateInvoiceReportByAccountIdInPDF";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string InitializationBeforeSend = "InitializationBeforeSend";
            public const string SendReport = "SendReport";
            public const string GetCustomersSearchResults = "GetCustomersSearchResults";
            public const string AddReceiver = "AddReceiver";
            public const string GetSendingConfirmationPartialView = "GetSendingConfirmationPartialView";
            public const string CreateExcelReportForCurrentCreditOfAccounts = "CreateExcelReportForCurrentCreditOfAccounts";
            public const string CreateInvoiceReportByAccountIdInPDF = "CreateInvoiceReportByAccountIdInPDF";
        }


        static readonly ActionParamsClass_InitializationBeforeSend s_params_InitializationBeforeSend = new ActionParamsClass_InitializationBeforeSend();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InitializationBeforeSend InitializationBeforeSendParams { get { return s_params_InitializationBeforeSend; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InitializationBeforeSend
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetCustomersSearchResults s_params_GetCustomersSearchResults = new ActionParamsClass_GetCustomersSearchResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCustomersSearchResults GetCustomersSearchResultsParams { get { return s_params_GetCustomersSearchResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCustomersSearchResults
        {
            public readonly string customerName = "customerName";
        }
        static readonly ActionParamsClass_AddReceiver s_params_AddReceiver = new ActionParamsClass_AddReceiver();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddReceiver AddReceiverParams { get { return s_params_AddReceiver; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddReceiver
        {
            public readonly string customerId = "customerId";
        }
        static readonly ActionParamsClass_GetSendingConfirmationPartialView s_params_GetSendingConfirmationPartialView = new ActionParamsClass_GetSendingConfirmationPartialView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSendingConfirmationPartialView GetSendingConfirmationPartialViewParams { get { return s_params_GetSendingConfirmationPartialView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSendingConfirmationPartialView
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_CreateInvoiceReportByAccountIdInPDF s_params_CreateInvoiceReportByAccountIdInPDF = new ActionParamsClass_CreateInvoiceReportByAccountIdInPDF();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateInvoiceReportByAccountIdInPDF CreateInvoiceReportByAccountIdInPDFParams { get { return s_params_CreateInvoiceReportByAccountIdInPDF; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateInvoiceReportByAccountIdInPDF
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string SendReport = "SendReport";
                public readonly string ShowPDFReport = "ShowPDFReport";
            }
            public readonly string SendReport = "~/Views/Report/SendReport.cshtml";
            public readonly string ShowPDFReport = "~/Views/Report/ShowPDFReport.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReportController : MvcEshop.Controllers.ReportController
    {
        public T4MVC_ReportController() : base(Dummy.Instance) { }

        [NonAction]
        partial void InitializationBeforeSendOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InitializationBeforeSend(System.Guid? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InitializationBeforeSend);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InitializationBeforeSendOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SendReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendReport);
            SendReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCustomersSearchResultsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string customerName);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetCustomersSearchResults(string customerName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetCustomersSearchResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerName", customerName);
            GetCustomersSearchResultsOverride(callInfo, customerName);
            return callInfo;
        }

        [NonAction]
        partial void AddReceiverOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string customerId);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddReceiver(string customerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddReceiver);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            AddReceiverOverride(callInfo, customerId);
            return callInfo;
        }

        [NonAction]
        partial void GetSendingConfirmationPartialViewOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string email);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetSendingConfirmationPartialView(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetSendingConfirmationPartialView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            GetSendingConfirmationPartialViewOverride(callInfo, email);
            return callInfo;
        }

        [NonAction]
        partial void CreateExcelReportForCurrentCreditOfAccountsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateExcelReportForCurrentCreditOfAccounts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateExcelReportForCurrentCreditOfAccounts);
            CreateExcelReportForCurrentCreditOfAccountsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateInvoiceReportByAccountIdInPDFOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateInvoiceReportByAccountIdInPDF(System.Guid? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateInvoiceReportByAccountIdInPDF);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CreateInvoiceReportByAccountIdInPDFOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
