//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationSettings {
        
        /// <summary>
        ///   Looks up a localized string similar to: Application Copyright Text
        /// </summary>
        public static string ApplicationCopyrightText([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ApplicationCopyrightText;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ApplicationCopyrightText", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Application Name
        /// </summary>
        public static string ApplicationName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ApplicationName;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ApplicationName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Application Version
        /// </summary>
        public static string ApplicationVersion([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ApplicationVersion;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ApplicationVersion", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Should User Attach File in Contact Us Page
        /// </summary>
        public static string CanUserAttachFileInContactUsPage([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.CanUserAttachFileInContactUsPage;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("CanUserAttachFileInContactUsPage", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Can User Search The Others
        /// </summary>
        public static string CanUserSearchTheOthers([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.CanUserSearchTheOthers;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("CanUserSearchTheOthers", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Check National Code
        /// </summary>
        public static string CheckNationalCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.CheckNationalCode;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("CheckNationalCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Current User Profile Level
        /// </summary>
        public static string CurrentUserProfileLevel([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.CurrentUserProfileLevel;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("CurrentUserProfileLevel", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Application Settings
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.EntityName;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Force User To Update Profile After Login
        /// </summary>
        public static string ForceUserToUpdateProfileAfterLogin([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ForceUserToUpdateProfileAfterLogin;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ForceUserToUpdateProfileAfterLogin", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Captcha Image Enabled
        /// </summary>
        public static string IsCaptchaImageEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsCaptchaImageEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsCaptchaImageEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Cms Enabled
        /// </summary>
        public static string IsCmsEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsCmsEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsCmsEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Lms Enabled
        /// </summary>
        public static string IsLmsEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsLmsEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsLmsEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Registration Enabled
        /// </summary>
        public static string IsRegistrationEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsRegistrationEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsRegistrationEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is SMS Service Enabled
        /// </summary>
        public static string IsSmsServiceEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsSmsServiceEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsSmsServiceEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Ssl Enabled
        /// </summary>
        public static string IsSslEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsSslEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsSslEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Ssl Enabled
        /// </summary>
        public static string IsSssEnabled([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsSssEnabled;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsSssEnabled", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is User Email Verification Required For Login
        /// </summary>
        public static string IsUserEmailVerificationRequiredForLogin([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.IsUserEmailVerificationRequiredForLogin;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("IsUserEmailVerificationRequiredForLogin", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Master Password
        /// </summary>
        public static string MasterPassword([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.MasterPassword;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("MasterPassword", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Server Time Zone Difference
        /// </summary>
        public static string ServerTimeZoneDifference([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ServerTimeZoneDifference;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ServerTimeZoneDifference", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Should User Be Activated After Registration
        /// </summary>
        public static string ShouldUserBeActivatedAfterRegistration([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.ShouldUserBeActivatedAfterRegistration;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("ShouldUserBeActivatedAfterRegistration", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sms Center Number
        /// </summary>
        public static string SmsCenterNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.SmsCenterNumber;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("SmsCenterNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sms Center Password
        /// </summary>
        public static string SmsCenterPassword([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.SmsCenterPassword;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("SmsCenterPassword", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sms Center Username
        /// </summary>
        public static string SmsCenterUsername([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.SmsCenterUsername;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("SmsCenterUsername", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Total User Count
        /// </summary>
        public static string TotalUserCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ApplicationSettings.TotalUserCount;
            }
            return global::Models.Resources.ApplicationSettings.ResourceManager.GetString("TotalUserCount", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationSettingsKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Application Copyright Text
        /// </summary>
        public const string ApplicationCopyrightText = "ApplicationCopyrightText";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Application Name
        /// </summary>
        public const string ApplicationName = "ApplicationName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Application Version
        /// </summary>
        public const string ApplicationVersion = "ApplicationVersion";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Should User Attach File in Contact Us Page
        /// </summary>
        public const string CanUserAttachFileInContactUsPage = "CanUserAttachFileInContactUsPage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Can User Search The Others
        /// </summary>
        public const string CanUserSearchTheOthers = "CanUserSearchTheOthers";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Check National Code
        /// </summary>
        public const string CheckNationalCode = "CheckNationalCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Current User Profile Level
        /// </summary>
        public const string CurrentUserProfileLevel = "CurrentUserProfileLevel";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Application Settings
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Force User To Update Profile After Login
        /// </summary>
        public const string ForceUserToUpdateProfileAfterLogin = "ForceUserToUpdateProfileAfterLogin";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Captcha Image Enabled
        /// </summary>
        public const string IsCaptchaImageEnabled = "IsCaptchaImageEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Cms Enabled
        /// </summary>
        public const string IsCmsEnabled = "IsCmsEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Lms Enabled
        /// </summary>
        public const string IsLmsEnabled = "IsLmsEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Registration Enabled
        /// </summary>
        public const string IsRegistrationEnabled = "IsRegistrationEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is SMS Service Enabled
        /// </summary>
        public const string IsSmsServiceEnabled = "IsSmsServiceEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Ssl Enabled
        /// </summary>
        public const string IsSslEnabled = "IsSslEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Ssl Enabled
        /// </summary>
        public const string IsSssEnabled = "IsSssEnabled";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is User Email Verification Required For Login
        /// </summary>
        public const string IsUserEmailVerificationRequiredForLogin = "IsUserEmailVerificationRequiredForLogin";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Master Password
        /// </summary>
        public const string MasterPassword = "MasterPassword";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Server Time Zone Difference
        /// </summary>
        public const string ServerTimeZoneDifference = "ServerTimeZoneDifference";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Should User Be Activated After Registration
        /// </summary>
        public const string ShouldUserBeActivatedAfterRegistration = "ShouldUserBeActivatedAfterRegistration";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sms Center Number
        /// </summary>
        public const string SmsCenterNumber = "SmsCenterNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sms Center Password
        /// </summary>
        public const string SmsCenterPassword = "SmsCenterPassword";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sms Center Username
        /// </summary>
        public const string SmsCenterUsername = "SmsCenterUsername";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Total User Count
        /// </summary>
        public const string TotalUserCount = "TotalUserCount";
    }
}
