//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class File {
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Description;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Download Count
        /// </summary>
        public static string DownloadCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.DownloadCount;
            }
            return global::Models.Resources.File.ResourceManager.GetString("DownloadCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Files
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.EntitiesName;
            }
            return global::Models.Resources.File.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Files of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.EntitiesNameOf;
            }
            return global::Models.Resources.File.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: File
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.EntityName;
            }
            return global::Models.Resources.File.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: File of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.EntityNameOf;
            }
            return global::Models.Resources.File.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Extension
        /// </summary>
        public static string Extension([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Extension;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Extension", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Accessible From The Other Sites
        /// </summary>
        public static string IsAccessibleFromTheOtherSites([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.IsAccessibleFromTheOtherSites;
            }
            return global::Models.Resources.File.ResourceManager.GetString("IsAccessibleFromTheOtherSites", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Direct Accessible
        /// </summary>
        public static string IsDirectAccessible([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.IsDirectAccessible;
            }
            return global::Models.Resources.File.ResourceManager.GetString("IsDirectAccessible", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Keywords
        /// </summary>
        public static string Keywords([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Keywords;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Keywords", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Length
        /// </summary>
        public static string Length([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Length;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Length", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Name;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Original Name
        /// </summary>
        public static string OriginalName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.OriginalName;
            }
            return global::Models.Resources.File.ResourceManager.GetString("OriginalName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Tags
        /// </summary>
        public static string Tags([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Tags;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Tags", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.File.Title;
            }
            return global::Models.Resources.File.ResourceManager.GetString("Title", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FileKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Download Count
        /// </summary>
        public const string DownloadCount = "DownloadCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Files
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Files of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: File
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: File of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Extension
        /// </summary>
        public const string Extension = "Extension";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Accessible From The Other Sites
        /// </summary>
        public const string IsAccessibleFromTheOtherSites = "IsAccessibleFromTheOtherSites";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Direct Accessible
        /// </summary>
        public const string IsDirectAccessible = "IsDirectAccessible";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Keywords
        /// </summary>
        public const string Keywords = "Keywords";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Length
        /// </summary>
        public const string Length = "Length";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Original Name
        /// </summary>
        public const string OriginalName = "OriginalName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Tags
        /// </summary>
        public const string Tags = "Tags";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Title
        /// </summary>
        public const string Title = "Title";
    }
}
