//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Folder {
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Folder.Description;
            }
            return global::Models.Resources.Folder.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Visible
        /// </summary>
        public static string IsVisible([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Folder.IsVisible;
            }
            return global::Models.Resources.Folder.ResourceManager.GetString("IsVisible", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Folder.Name;
            }
            return global::Models.Resources.Folder.ResourceManager.GetString("Name", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FolderKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Visible
        /// </summary>
        public const string IsVisible = "IsVisible";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
    }
}
