//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Gender {
        
        /// <summary>
        ///   Looks up a localized string similar to: Code
        /// </summary>
        public static string Code([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.Code;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("Code", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Genders
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.EntitiesName;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Genders of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.EntitiesNameOf;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Gender
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.EntityName;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Gender of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.EntityNameOf;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name 1
        /// </summary>
        public static string Name1([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.Name1;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("Name1", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name 2
        /// </summary>
        public static string Name2([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.Name2;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("Name2", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name 3
        /// </summary>
        public static string Name3([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.Name3;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("Name3", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name 4
        /// </summary>
        public static string Name4([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Gender.Name4;
            }
            return global::Models.Resources.Gender.ResourceManager.GetString("Name4", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.1.1")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GenderKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Code
        /// </summary>
        public const string Code = "Code";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Genders
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Genders of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Gender
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Gender of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name 1
        /// </summary>
        public const string Name1 = "Name1";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name 2
        /// </summary>
        public const string Name2 = "Name2";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name 3
        /// </summary>
        public const string Name3 = "Name3";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name 4
        /// </summary>
        public const string Name4 = "Name4";
    }
}
