//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MailSettings {
        
        /// <summary>
        ///   Looks up a localized string similar to: Bcc Addresses
        /// </summary>
        public static string BccAddresses([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.BccAddresses;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("BccAddresses", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Subject Template
        /// </summary>
        public static string EmailSubjectTemplate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.EmailSubjectTemplate;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("EmailSubjectTemplate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: All of Mail Settings
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.EntitiesName;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: All of Mail Settings of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.EntitiesNameOf;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Mail Settings
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.EntityName;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Mail Settings of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.EntityNameOf;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.Name;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sender Display Name
        /// </summary>
        public static string SenderDisplayName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SenderDisplayName;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SenderDisplayName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sender Email Address
        /// </summary>
        public static string SenderEmailAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SenderEmailAddress;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SenderEmailAddress", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sender Email Password
        /// </summary>
        public static string SenderEmailPassword([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SenderEmailPassword;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SenderEmailPassword", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Smtp Client Enable Ssl
        /// </summary>
        public static string SmtpClientEnableSsl([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SmtpClientEnableSsl;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SmtpClientEnableSsl", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Smtp Client Host Address
        /// </summary>
        public static string SmtpClientHostAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SmtpClientHostAddress;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SmtpClientHostAddress", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Smtp Client Port Number
        /// </summary>
        public static string SmtpClientPortNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SmtpClientPortNumber;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SmtpClientPortNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Smtp Client Timeout
        /// </summary>
        public static string SmtpClientTimeout([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SmtpClientTimeout;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SmtpClientTimeout", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Support Display Name
        /// </summary>
        public static string SupportDisplayName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SupportDisplayName;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SupportDisplayName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Support Email Address
        /// </summary>
        public static string SupportEmailAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.MailSettings.SupportEmailAddress;
            }
            return global::Models.Resources.MailSettings.ResourceManager.GetString("SupportEmailAddress", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MailSettingsKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Bcc Addresses
        /// </summary>
        public const string BccAddresses = "BccAddresses";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Subject Template
        /// </summary>
        public const string EmailSubjectTemplate = "EmailSubjectTemplate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: All of Mail Settings
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: All of Mail Settings of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Mail Settings
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Mail Settings of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sender Display Name
        /// </summary>
        public const string SenderDisplayName = "SenderDisplayName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sender Email Address
        /// </summary>
        public const string SenderEmailAddress = "SenderEmailAddress";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sender Email Password
        /// </summary>
        public const string SenderEmailPassword = "SenderEmailPassword";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Smtp Client Enable Ssl
        /// </summary>
        public const string SmtpClientEnableSsl = "SmtpClientEnableSsl";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Smtp Client Host Address
        /// </summary>
        public const string SmtpClientHostAddress = "SmtpClientHostAddress";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Smtp Client Port Number
        /// </summary>
        public const string SmtpClientPortNumber = "SmtpClientPortNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Smtp Client Timeout
        /// </summary>
        public const string SmtpClientTimeout = "SmtpClientTimeout";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Support Display Name
        /// </summary>
        public const string SupportDisplayName = "SupportDisplayName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Support Email Address
        /// </summary>
        public const string SupportEmailAddress = "SupportEmailAddress";
    }
}
