//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ProjectArea {
        
        /// <summary>
        ///   Looks up a localized string similar to: Areas
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.EntitiesName;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Areas of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.EntitiesNameOf;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Area
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.EntityName;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Area of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.EntityNameOf;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The name is already exist! Please choose another one.
        /// </summary>
        public static string Error001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.Error001;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("Error001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Section(s)
        /// </summary>
        public static string ProjectControllerCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.ProjectArea.ProjectControllerCount;
            }
            return global::Models.Resources.ProjectArea.ResourceManager.GetString("ProjectControllerCount", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ProjectAreaKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Areas
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Areas of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Area
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Area of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The name is already exist! Please choose another one.
        /// </summary>
        public const string Error001 = "Error001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Section(s)
        /// </summary>
        public const string ProjectControllerCount = "ProjectControllerCount";
    }
}
