//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class User {
        
        /// <summary>
        ///   Looks up a localized string similar to: Account Expire Date
        /// </summary>
        public static string AccountExpireDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.AccountExpireDate;
            }
            return global::Models.Resources.User.ResourceManager.GetString("AccountExpireDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Account Terminate Date Time
        /// </summary>
        public static string AccountTerminateDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.AccountTerminateDateTime;
            }
            return global::Models.Resources.User.ResourceManager.GetString("AccountTerminateDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Address
        /// </summary>
        public static string Address([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Address;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Address", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Administrator Description
        /// </summary>
        public static string AdministratorDescription([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.AdministratorDescription;
            }
            return global::Models.Resources.User.ResourceManager.GetString("AdministratorDescription", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Age
        /// </summary>
        public static string Age([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Age;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Age", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Avatar
        /// </summary>
        public static string Avatar([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Avatar;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Avatar", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Birth Date
        /// </summary>
        public static string BirthDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.BirthDate;
            }
            return global::Models.Resources.User.ResourceManager.GetString("BirthDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell Phone Number
        /// </summary>
        public static string CellPhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.CellPhoneNumber;
            }
            return global::Models.Resources.User.ResourceManager.GetString("CellPhoneNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell Phone Number Verification Key
        /// </summary>
        public static string CellPhoneNumberVerificationKey([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.CellPhoneNumberVerificationKey;
            }
            return global::Models.Resources.User.ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Company Name
        /// </summary>
        public static string CompanyName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.CompanyName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("CompanyName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Description;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address
        /// </summary>
        public static string EmailAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EmailAddress;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EmailAddress", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address Verification Key
        /// </summary>
        public static string EmailAddressVerificationKey([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EmailAddressVerificationKey;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Users
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EntitiesName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Users of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EntitiesNameOf;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EntityName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.EntityNameOf;
            }
            return global::Models.Resources.User.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address is already exist! Please choose another one.
        /// </summary>
        public static string Error001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error001;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: There is no any user with this email address!
        /// </summary>
        public static string Error002([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error002;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error002", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Username and/or Password is not correct! Please try again...
        /// </summary>
        public static string Error003([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error003;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error003", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell Phone Number is already exist! Please choose another one.
        /// </summary>
        public static string Error004([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error004;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error004", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Your email address was not verified! Please check your email box.
        /// </summary>
        public static string Error005([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error005;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error005", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You should not login at this time! Please contact support.
        /// </summary>
        public static string Error006([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error006;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error006", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Your email address has been already verified!
        /// </summary>
        public static string Error007([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error007;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error007", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify correct current password!
        /// </summary>
        public static string Error008([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error008;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error008", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell phone number verification key is not valid!
        /// </summary>
        public static string Error009([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error009;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error009", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: National Code is not Valid!
        /// </summary>
        public static string Error010([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Error010;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Error010", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: First Name
        /// </summary>
        public static string FirstName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.FirstName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("FirstName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Full Name
        /// </summary>
        public static string FullName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.FullName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("FullName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Gender
        /// </summary>
        public static string Gender([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Gender;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Gender", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Has Avatar
        /// </summary>
        public static string HasAvatar([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.HasAvatar;
            }
            return global::Models.Resources.User.ResourceManager.GetString("HasAvatar", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Has Resume
        /// </summary>
        public static string HasResume([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.HasResume;
            }
            return global::Models.Resources.User.ResourceManager.GetString("HasResume", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Hits
        /// </summary>
        public static string Hits([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Hits;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Hits", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Http Referer
        /// </summary>
        public static string HttpReferer([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.HttpReferer;
            }
            return global::Models.Resources.User.ResourceManager.GetString("HttpReferer", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Your registration done. We sent you an email for verification.
        /// </summary>
        public static string Information001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information001;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: We send again the email address verification key.
        /// </summary>
        public static string Information002([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information002;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information002", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: We generated a nice password and sent it to your email.
        /// </summary>
        public static string Information003([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information003;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information003", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The new password has been set for the user.
        /// </summary>
        public static string Information004([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information004;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information004", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The new password has been set.
        /// </summary>
        public static string Information005([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information005;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information005", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: We sent again a SMS for your mobile verification.
        /// </summary>
        public static string Information006([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information006;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information006", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Your cell phone number is verified
        /// </summary>
        public static string Information007([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Information007;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Information007", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Account Expirable
        /// </summary>
        public static string IsAccountExpirable([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsAccountExpirable;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsAccountExpirable", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Account Terminated
        /// </summary>
        public static string IsAccountTerminated([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsAccountTerminated;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsAccountTerminated", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Address Public
        /// </summary>
        public static string IsAddressPublic([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsAddressPublic;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsAddressPublic", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Birth Date Public
        /// </summary>
        public static string IsBirthDatePublic([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsBirthDatePublic;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsBirthDatePublic", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Cell Phone Number Public
        /// </summary>
        public static string IsCellPhoneNumberPublic([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsCellPhoneNumberPublic;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsCellPhoneNumberPublic", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell Phone Number Verified
        /// </summary>
        public static string IsCellPhoneNumberVerified([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsCellPhoneNumberVerified;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Direct Contactable
        /// </summary>
        public static string IsDirectContactable([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsDirectContactable;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsDirectContactable", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Email Address Public
        /// </summary>
        public static string IsEmailAddressPublic([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsEmailAddressPublic;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsEmailAddressPublic", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address Verified
        /// </summary>
        public static string IsEmailAddressVerified([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsEmailAddressVerified;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Black List
        /// </summary>
        public static string IsInBlackList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsInBlackList;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsInBlackList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Profile is Public
        /// </summary>
        public static string IsProfilePublic([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.IsProfilePublic;
            }
            return global::Models.Resources.User.ResourceManager.GetString("IsProfilePublic", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Job Title
        /// </summary>
        public static string JobTitle([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.JobTitle;
            }
            return global::Models.Resources.User.ResourceManager.GetString("JobTitle", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Last Login Date Time
        /// </summary>
        public static string LastLoginDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.LastLoginDateTime;
            }
            return global::Models.Resources.User.ResourceManager.GetString("LastLoginDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Last Name
        /// </summary>
        public static string LastName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.LastName;
            }
            return global::Models.Resources.User.ResourceManager.GetString("LastName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Login Count
        /// </summary>
        public static string LoginCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.LoginCount;
            }
            return global::Models.Resources.User.ResourceManager.GetString("LoginCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: National Code
        /// </summary>
        public static string NationalCode([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.NationalCode;
            }
            return global::Models.Resources.User.ResourceManager.GetString("NationalCode", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Password
        /// </summary>
        public static string Password([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Password;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Password", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Profile Level
        /// </summary>
        public static string ProfileLevel([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ProfileLevel;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ProfileLevel", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Register Date Time
        /// </summary>
        public static string RegisterDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.RegisterDateTime;
            }
            return global::Models.Resources.User.ResourceManager.GetString("RegisterDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Register IP
        /// </summary>
        public static string RegisterIP([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.RegisterIP;
            }
            return global::Models.Resources.User.ResourceManager.GetString("RegisterIP", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Reset Password Date Time
        /// </summary>
        public static string ResetPasswordDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ResetPasswordDateTime;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ResetPasswordDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Reset Password Verification Key
        /// </summary>
        public static string ResetPasswordVerificationKey([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ResetPasswordVerificationKey;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ResetPasswordVerificationKey", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Resume
        /// </summary>
        public static string Resume([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Resume;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Resume", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Role
        /// </summary>
        public static string Role([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Role;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Role", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Shamsi Birth Day
        /// </summary>
        public static string ShamsiBirthD([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ShamsiBirthD;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ShamsiBirthD", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Shamsi Birth Month
        /// </summary>
        public static string ShamsiBirthM([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ShamsiBirthM;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ShamsiBirthM", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Shamsi Birth Year
        /// </summary>
        public static string ShamsiBirthY([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.ShamsiBirthY;
            }
            return global::Models.Resources.User.ResourceManager.GetString("ShamsiBirthY", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Update Profile Date Time
        /// </summary>
        public static string UpdateProfileDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.UpdateProfileDateTime;
            }
            return global::Models.Resources.User.ResourceManager.GetString("UpdateProfileDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Users List
        /// </summary>
        public static string UsersList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.UsersList;
            }
            return global::Models.Resources.User.ResourceManager.GetString("UsersList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Verified Email Address or Cell Phone Number
        /// </summary>
        public static string VerifiedEmailAddressOrCellPhoneNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.VerifiedEmailAddressOrCellPhoneNumber;
            }
            return global::Models.Resources.User.ResourceManager.GetString("VerifiedEmailAddressOrCellPhoneNumber", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: This user has full control and it does not need any permission!
        /// </summary>
        public static string Warning001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.User.Warning001;
            }
            return global::Models.Resources.User.ResourceManager.GetString("Warning001", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Account Expire Date
        /// </summary>
        public const string AccountExpireDate = "AccountExpireDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Account Terminate Date Time
        /// </summary>
        public const string AccountTerminateDateTime = "AccountTerminateDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Address
        /// </summary>
        public const string Address = "Address";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Administrator Description
        /// </summary>
        public const string AdministratorDescription = "AdministratorDescription";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Age
        /// </summary>
        public const string Age = "Age";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Avatar
        /// </summary>
        public const string Avatar = "Avatar";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Birth Date
        /// </summary>
        public const string BirthDate = "BirthDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell Phone Number
        /// </summary>
        public const string CellPhoneNumber = "CellPhoneNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell Phone Number Verification Key
        /// </summary>
        public const string CellPhoneNumberVerificationKey = "CellPhoneNumberVerificationKey";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Company Name
        /// </summary>
        public const string CompanyName = "CompanyName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address
        /// </summary>
        public const string EmailAddress = "EmailAddress";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address Verification Key
        /// </summary>
        public const string EmailAddressVerificationKey = "EmailAddressVerificationKey";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Users
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Users of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address is already exist! Please choose another one.
        /// </summary>
        public const string Error001 = "Error001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: There is no any user with this email address!
        /// </summary>
        public const string Error002 = "Error002";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Username and/or Password is not correct! Please try again...
        /// </summary>
        public const string Error003 = "Error003";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell Phone Number is already exist! Please choose another one.
        /// </summary>
        public const string Error004 = "Error004";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Your email address was not verified! Please check your email box.
        /// </summary>
        public const string Error005 = "Error005";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You should not login at this time! Please contact support.
        /// </summary>
        public const string Error006 = "Error006";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Your email address has been already verified!
        /// </summary>
        public const string Error007 = "Error007";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify correct current password!
        /// </summary>
        public const string Error008 = "Error008";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell phone number verification key is not valid!
        /// </summary>
        public const string Error009 = "Error009";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: National Code is not Valid!
        /// </summary>
        public const string Error010 = "Error010";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: First Name
        /// </summary>
        public const string FirstName = "FirstName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Full Name
        /// </summary>
        public const string FullName = "FullName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Gender
        /// </summary>
        public const string Gender = "Gender";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Has Avatar
        /// </summary>
        public const string HasAvatar = "HasAvatar";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Has Resume
        /// </summary>
        public const string HasResume = "HasResume";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Hits
        /// </summary>
        public const string Hits = "Hits";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Http Referer
        /// </summary>
        public const string HttpReferer = "HttpReferer";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Your registration done. We sent you an email for verification.
        /// </summary>
        public const string Information001 = "Information001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: We send again the email address verification key.
        /// </summary>
        public const string Information002 = "Information002";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: We generated a nice password and sent it to your email.
        /// </summary>
        public const string Information003 = "Information003";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The new password has been set for the user.
        /// </summary>
        public const string Information004 = "Information004";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The new password has been set.
        /// </summary>
        public const string Information005 = "Information005";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: We sent again a SMS for your mobile verification.
        /// </summary>
        public const string Information006 = "Information006";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Your cell phone number is verified
        /// </summary>
        public const string Information007 = "Information007";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Account Expirable
        /// </summary>
        public const string IsAccountExpirable = "IsAccountExpirable";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Account Terminated
        /// </summary>
        public const string IsAccountTerminated = "IsAccountTerminated";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Address Public
        /// </summary>
        public const string IsAddressPublic = "IsAddressPublic";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Birth Date Public
        /// </summary>
        public const string IsBirthDatePublic = "IsBirthDatePublic";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Cell Phone Number Public
        /// </summary>
        public const string IsCellPhoneNumberPublic = "IsCellPhoneNumberPublic";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell Phone Number Verified
        /// </summary>
        public const string IsCellPhoneNumberVerified = "IsCellPhoneNumberVerified";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Direct Contactable
        /// </summary>
        public const string IsDirectContactable = "IsDirectContactable";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Email Address Public
        /// </summary>
        public const string IsEmailAddressPublic = "IsEmailAddressPublic";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address Verified
        /// </summary>
        public const string IsEmailAddressVerified = "IsEmailAddressVerified";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Black List
        /// </summary>
        public const string IsInBlackList = "IsInBlackList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Profile is Public
        /// </summary>
        public const string IsProfilePublic = "IsProfilePublic";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Job Title
        /// </summary>
        public const string JobTitle = "JobTitle";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Last Login Date Time
        /// </summary>
        public const string LastLoginDateTime = "LastLoginDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Last Name
        /// </summary>
        public const string LastName = "LastName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Login Count
        /// </summary>
        public const string LoginCount = "LoginCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: National Code
        /// </summary>
        public const string NationalCode = "NationalCode";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Password
        /// </summary>
        public const string Password = "Password";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Profile Level
        /// </summary>
        public const string ProfileLevel = "ProfileLevel";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Register Date Time
        /// </summary>
        public const string RegisterDateTime = "RegisterDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Register IP
        /// </summary>
        public const string RegisterIP = "RegisterIP";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Reset Password Date Time
        /// </summary>
        public const string ResetPasswordDateTime = "ResetPasswordDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Reset Password Verification Key
        /// </summary>
        public const string ResetPasswordVerificationKey = "ResetPasswordVerificationKey";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Resume
        /// </summary>
        public const string Resume = "Resume";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Role
        /// </summary>
        public const string Role = "Role";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Shamsi Birth Day
        /// </summary>
        public const string ShamsiBirthD = "ShamsiBirthD";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Shamsi Birth Month
        /// </summary>
        public const string ShamsiBirthM = "ShamsiBirthM";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Shamsi Birth Year
        /// </summary>
        public const string ShamsiBirthY = "ShamsiBirthY";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Update Profile Date Time
        /// </summary>
        public const string UpdateProfileDateTime = "UpdateProfileDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Users List
        /// </summary>
        public const string UsersList = "UsersList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Verified Email Address or Cell Phone Number
        /// </summary>
        public const string VerifiedEmailAddressOrCellPhoneNumber = "VerifiedEmailAddressOrCellPhoneNumber";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: This user has full control and it does not need any permission!
        /// </summary>
        public const string Warning001 = "Warning001";
    }
}
