//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserLoginLog {
        
        /// <summary>
        ///   Looks up a localized string similar to: User Login Logs
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.EntitiesName;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User Login Logs of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.EntitiesNameOf;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User Login Log
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.EntityName;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User Login Log of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.EntityNameOf;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Hidden
        /// </summary>
        public static string Hidden([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.Hidden;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("Hidden", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: IP
        /// </summary>
        public static string IP([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.IP;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("IP", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Hidden
        /// </summary>
        public static string IsHidden([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.IsHidden;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("IsHidden", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Login Date Time
        /// </summary>
        public static string LoginDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.LoginDateTime;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("LoginDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Logout Date Time
        /// </summary>
        public static string LogoutDateTime([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.LogoutDateTime;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("LogoutDateTime", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Online Users
        /// </summary>
        public static string OnlineUsers([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.OnlineUsers;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("OnlineUsers", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Session Id
        /// </summary>
        public static string SessionId([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.UserLoginLog.SessionId;
            }
            return global::Models.Resources.UserLoginLog.ResourceManager.GetString("SessionId", resourceCulture);
        }
    }
}
namespace Models.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserLoginLogKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User Login Logs
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User Login Logs of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User Login Log
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User Login Log of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Hidden
        /// </summary>
        public const string Hidden = "Hidden";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: IP
        /// </summary>
        public const string IP = "IP";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Hidden
        /// </summary>
        public const string IsHidden = "IsHidden";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Login Date Time
        /// </summary>
        public const string LoginDateTime = "LoginDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Logout Date Time
        /// </summary>
        public const string LogoutDateTime = "LogoutDateTime";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Online Users
        /// </summary>
        public const string OnlineUsers = "OnlineUsers";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Session Id
        /// </summary>
        public const string SessionId = "SessionId";
    }
}
