//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class General {
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Channel Description
        /// </summary>
        public static string RssChannelDescription([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssChannelDescription;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssChannelDescription", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Channel Link
        /// </summary>
        public static string RssChannelLink([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssChannelLink;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssChannelLink", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Channel Title
        /// </summary>
        public static string RssChannelTitle([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssChannelTitle;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssChannelTitle", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Image Link
        /// </summary>
        public static string RssImageLink([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssImageLink;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssImageLink", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Image Title
        /// </summary>
        public static string RssImageTitle([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssImageTitle;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssImageTitle", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Image Url
        /// </summary>
        public static string RssImageUrl([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssImageUrl;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssImageUrl", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Item Count
        /// </summary>
        public static string RssItemCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssItemCount;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssItemCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rss Root Creator Url
        /// </summary>
        public static string RssRootCreatorUrl([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.General.RssRootCreatorUrl;
            }
            return global::Models.Resources.Cms.General.ResourceManager.GetString("RssRootCreatorUrl", resourceCulture);
        }
    }
}
namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GeneralKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Channel Description
        /// </summary>
        public const string RssChannelDescription = "RssChannelDescription";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Channel Link
        /// </summary>
        public const string RssChannelLink = "RssChannelLink";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Channel Title
        /// </summary>
        public const string RssChannelTitle = "RssChannelTitle";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Image Link
        /// </summary>
        public const string RssImageLink = "RssImageLink";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Image Title
        /// </summary>
        public const string RssImageTitle = "RssImageTitle";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Image Url
        /// </summary>
        public const string RssImageUrl = "RssImageUrl";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Item Count
        /// </summary>
        public const string RssItemCount = "RssItemCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rss Root Creator Url
        /// </summary>
        public const string RssRootCreatorUrl = "RssRootCreatorUrl";
    }
}
