//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Layout {
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Description;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Dynamic Page Count
        /// </summary>
        public static string DynamicPageCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.DynamicPageCount;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("DynamicPageCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page Layouts
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.EntitiesName;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page Layouts Of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.EntitiesNameOf;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page Layout
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.EntityName;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page Layout Of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.EntityNameOf;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: -----
        /// </summary>
        public static string Error001([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Error001;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Error001", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: -----
        /// </summary>
        public static string Error002([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Error002;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Error002", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: -----
        /// </summary>
        public static string Error003([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Error003;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Error003", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Name;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Static Page Count
        /// </summary>
        public static string StaticPageCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.StaticPageCount;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("StaticPageCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Layout.Title;
            }
            return global::Models.Resources.Cms.Layout.ResourceManager.GetString("Title", resourceCulture);
        }
    }
}
namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class LayoutKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Dynamic Page Count
        /// </summary>
        public const string DynamicPageCount = "DynamicPageCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page Layouts
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page Layouts Of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page Layout
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page Layout Of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: -----
        /// </summary>
        public const string Error001 = "Error001";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: -----
        /// </summary>
        public const string Error002 = "Error002";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: -----
        /// </summary>
        public const string Error003 = "Error003";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Static Page Count
        /// </summary>
        public const string StaticPageCount = "StaticPageCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Title
        /// </summary>
        public const string Title = "Title";
    }
}
