//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Tag {
        
        /// <summary>
        ///   Looks up a localized string similar to: Tags
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.EntitiesName;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Tags of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.EntitiesNameOf;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Tag
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.EntityName;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Tag of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.EntityNameOf;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.Name;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page Count
        /// </summary>
        public static string PageCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PageCount;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PageCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Page List
        /// </summary>
        public static string PageList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PageList;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PageList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Photo Count
        /// </summary>
        public static string PhotoCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PhotoCount;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PhotoCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Photo List
        /// </summary>
        public static string PhotoList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PhotoList;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PhotoList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Post Count
        /// </summary>
        public static string PostCount([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PostCount;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PostCount", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Post List
        /// </summary>
        public static string PostList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Models.Resources.Cms.Tag.PostList;
            }
            return global::Models.Resources.Cms.Tag.ResourceManager.GetString("PostList", resourceCulture);
        }
    }
}
namespace Models.Resources.Cms.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class TagKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Tags
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Tags of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Tag
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Tag of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page Count
        /// </summary>
        public const string PageCount = "PageCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Page List
        /// </summary>
        public const string PageList = "PageList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Photo Count
        /// </summary>
        public const string PhotoCount = "PhotoCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Photo List
        /// </summary>
        public const string PhotoList = "PhotoList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Post Count
        /// </summary>
        public const string PostCount = "PostCount";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Post List
        /// </summary>
        public const string PostList = "PostList";
    }
}
