//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEshop.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AccountCredit
    {
        public AccountCredit
            (double usedVolume, double remainingVolume, DateTime expirationDate, string accountTitle)
        {
            Id = System.Guid.NewGuid();
            UsedVolume = usedVolume;
            RemainingVolume = remainingVolume;
            ExpirationDate =Infrastructure.Convert.ToDisplayDate(expirationDate);
            AccountTitle = accountTitle;
        }
        public System.Guid Id { get; set; }
        public double UsedVolume { get; set; }
        public string ExpirationDate { get; set; }
        public string AccountTitle { get; set; }
        public double RemainingVolume { get; set; }
    }
}
