//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEshop.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;


    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<User>();
            this.Assignments = new HashSet<Assignment>();

            ClassId = System.Guid.NewGuid();
            IsActive = true;
            IsDeleted = false;
        }

        public System.Guid ClassId { get; set; }
        public string Title { get; set; }
        public string EnrollmentPassword { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }

        [Display(ResourceType = typeof(Resources.DisplayNames), Name = "StartDate")]
        public string DisplayStartDate
        {
            get
            {
                return Infrastructure.Convert.ToDisplayDate
                    (Infrastructure.Convert.ToPersian(StartDate));
            }

        }

        [Display(ResourceType = typeof(Resources.DisplayNames), Name = "EndDate")]
        public string DisplayEndDate
        {
            get
            {
                return Infrastructure.Convert.ToDisplayDate
                            (Infrastructure.Convert.ToPersian(EndDate));
            }

        }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public System.Guid InstructorUserId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public virtual User Instructor { get; set; }
        public virtual User Creator { get; set; }
        public virtual ICollection<User> Students { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public System.Guid? AccountId { get; set; }
        public virtual Account Account { get; set; }
    }
}
