//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEshop.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CreditCard
    {
        public CreditCard()
        {

            UsedVolume = 0;
            CreateDate = System.DateTime.Now;
            AllocatedVolume = 0;

        }
        public System.Guid AccountId { get; set; }
        public System.Guid UserId { get; set; }
        public double AllocatedVolume { get; set; }
        public double UsedVolume { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime CreateDate { get; set; }

        public virtual Account Account { get; set; }
        public virtual User User { get; set; }

        [System.ComponentModel.DataAnnotations.Display(ResourceType = typeof(Resources.DisplayNames),
            Name = Resources.Strings.DisplayNamesKeys.ExpirationDateForVolumeUse)]
        public string DisplayExpirationDate
        {
            get
            {
                return Infrastructure.Convert.ToDisplayDate(ExpirationDate);
            }

        }

        public double RemainingVolume
        {
            get
            {
                return (AllocatedVolume - UsedVolume);
            }
        }

        public bool IsExpired
        {
            get
            {

                return (Infrastructure.Convert.ToMiladi(ExpirationDate) < DateTime.Now);
            }
        }


        public double UsedToAllocatedRatio()
        {
            return ((double)UsedVolume / AllocatedVolume * 100);
        }
    }
}
