//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFinderServiceErrorLog
    {
        public System.Guid ErrorLogId { get; set; }
        public System.Guid AssignmentFileId { get; set; }
        public string ErrorText { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual AssignmentFile AssignmentFile { get; set; }
    }
}
