//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveCode is not correct.
        /// </summary>
        public static string ActiveCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("ActiveCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment File Uploaded Successfully!.
        /// </summary>
        public static string AssignmentFileUploadedSuccessfully {
            get {
                return ResourceManager.GetString("AssignmentFileUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Done Successfully.
        /// </summary>
        public static string ChangeDoneSuccessfully {
            get {
                return ResourceManager.GetString("ChangeDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckBoxListValidator {
            get {
                return ResourceManager.GetString("CheckBoxListValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}.
        /// </summary>
        public static string CompareValidator {
            get {
                return ResourceManager.GetString("CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Link Was Sent To The Email.
        /// </summary>
        public static string ConfirmationLinkWasSentToTheEmail {
            get {
                return ResourceManager.GetString("ConfirmationLinkWasSentToTheEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConstantTariffFullDescription {
            get {
                return ResourceManager.GetString("ConstantTariffFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocFindReportSentSuccessfullyToThePanel {
            get {
                return ResourceManager.GetString("DocFindReportSentSuccessfullyToThePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailMessageDefaultGreetingForUser {
            get {
                return ResourceManager.GetString("EmailMessageDefaultGreetingForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailMessageForConfirmationLink.
        /// </summary>
        public static string EmailMessageForConfirmationLink {
            get {
                return ResourceManager.GetString("EmailMessageForConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailMessageForPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailMessageForPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailMessageForProfileActivation {
            get {
                return ResourceManager.GetString("EmailMessageForProfileActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailMessageLayout {
            get {
                return ResourceManager.GetString("EmailMessageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorInCreationOfSomeUsers {
            get {
                return ResourceManager.GetString("ErrorInCreationOfSomeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured in the web site. Please contact support..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not exist in the system..
        /// </summary>
        public static string ExistenceValidator {
            get {
                return ResourceManager.GetString("ExistenceValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExpirationDateForVolumeUseHasFinished {
            get {
                return ResourceManager.GetString("ExpirationDateForVolumeUseHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FailureInOnlinePayment {
            get {
                return ResourceManager.GetString("FailureInOnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Data Is Not Correct.
        /// </summary>
        public static string FieldDataIsNotCorrect {
            get {
                return ResourceManager.GetString("FieldDataIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileMustBeImage {
            get {
                return ResourceManager.GetString("FileMustBeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FloatTariffFullDescription {
            get {
                return ResourceManager.GetString("FloatTariffFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot My Password?.
        /// </summary>
        public static string ForgotMyPassword {
            get {
                return ResourceManager.GetString("ForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ItemWasSentSuccessfullyToEmail {
            get {
                return ResourceManager.GetString("ItemWasSentSuccessfullyToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Account Successfully.
        /// </summary>
        public static string JoinedAccountSuccessfully {
            get {
                return ResourceManager.GetString("JoinedAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MoneyTypeValidator {
            get {
                return ResourceManager.GetString("MoneyTypeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email Confirmation Code Is Not Correct.
        /// </summary>
        public static string NewEmailConfirmationCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("NewEmailConfirmationCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoCopyFound {
            get {
                return ResourceManager.GetString("NoCopyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoRequestCreated {
            get {
                return ResourceManager.GetString("NoRequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumOfWordCharsMustBeLessThan {
            get {
                return ResourceManager.GetString("NumOfWordCharsMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least one small letter, one capital letter and a digit and it&apos;s length must be at least 8 and at most 20 charactors..
        /// </summary>
        public static string PasswordPolicy_aA1__8_20 {
            get {
                return ResourceManager.GetString("PasswordPolicy_aA1__8_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PDFReportIsAttachedToTheMessage {
            get {
                return ResourceManager.GetString("PDFReportIsAttachedToTheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseChooseOneFile {
            get {
                return ResourceManager.GetString("PleaseChooseOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseType {
            get {
                return ResourceManager.GetString("PleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PleaseTypePartOfSth {
            get {
                return ResourceManager.GetString("PleaseTypePartOfSth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Activation Done Successfully.
        /// </summary>
        public static string ProfileActivationDoneSuccessfully {
            get {
                return ResourceManager.GetString("ProfileActivationDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your profile Created Successfully.
        /// </summary>
        public static string ProfileCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProfileIsInActive {
            get {
                return ResourceManager.GetString("ProfileIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RangeValidator {
            get {
                return ResourceManager.GetString("RangeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not valid.
        /// </summary>
        public static string RegularExpressionValidator {
            get {
                return ResourceManager.GetString("RegularExpressionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Is Ready.
        /// </summary>
        public static string ReportIsReady {
            get {
                return ResourceManager.GetString("ReportIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReportSentSuccessfullyToEmail {
            get {
                return ResourceManager.GetString("ReportSentSuccessfullyToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0}.
        /// </summary>
        public static string RequiredFieldValidator {
            get {
                return ResourceManager.GetString("RequiredFieldValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an option for {0}.
        /// </summary>
        public static string RequiredFieldValidatorForDropDownList {
            get {
                return ResourceManager.GetString("RequiredFieldValidatorForDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Is Not Ready Yet..
        /// </summary>
        public static string ResultIsNotReadyYet {
            get {
                return ResourceManager.GetString("ResultIsNotReadyYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SthDoneSuccessfully {
            get {
                return ResourceManager.GetString("SthDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SthHasFinishedForYou {
            get {
                return ResourceManager.GetString("SthHasFinishedForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SuccessInOnlinePayment {
            get {
                return ResourceManager.GetString("SuccessInOnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SuccessInSendingReportToOrganizationPanel {
            get {
                return ResourceManager.GetString("SuccessInSendingReportToOrganizationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextUploadedSuccessfully {
            get {
                return ResourceManager.GetString("TextUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextVolumeIsMoreThanRemainingVolume {
            get {
                return ResourceManager.GetString("TextVolumeIsMoreThanRemainingVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextVolumeIsMoreThanRemainingVolumeOfAccount {
            get {
                return ResourceManager.GetString("TextVolumeIsMoreThanRemainingVolumeOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has been registered by another one.
        /// </summary>
        public static string UniquenessValidator {
            get {
                return ResourceManager.GetString("UniquenessValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UploadingText {
            get {
                return ResourceManager.GetString("UploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UsedToAllocatedVolumePercentageHasFinishedForYourAccount {
            get {
                return ResourceManager.GetString("UsedToAllocatedVolumePercentageHasFinishedForYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserHasBeenAlreadyAddedToThisAccount {
            get {
                return ResourceManager.GetString("UserHasBeenAlreadyAddedToThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VolumeTypeValidator {
            get {
                return ResourceManager.GetString("VolumeTypeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeFreeUser {
            get {
                return ResourceManager.GetString("WelcomeFreeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! you are the account manager..
        /// </summary>
        public static string WelcomeToAccountManagerWhoIsNotRegistered {
            get {
                return ResourceManager.GetString("WelcomeToAccountManagerWhoIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! you are the account manager..
        /// </summary>
        public static string WelcomeToAccountManagerWhoIsRegistered {
            get {
                return ResourceManager.GetString("WelcomeToAccountManagerWhoIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeToSystem {
            get {
                return ResourceManager.GetString("WelcomeToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeToSystemExpertUserWhoIsNotRegistered {
            get {
                return ResourceManager.GetString("WelcomeToSystemExpertUserWhoIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! you are a new User..
        /// </summary>
        public static string WelcomeToUserWhoIsNotRegistered {
            get {
                return ResourceManager.GetString("WelcomeToUserWhoIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! you are a new User..
        /// </summary>
        public static string WelcomeToUserWhoIsRegistered {
            get {
                return ResourceManager.GetString("WelcomeToUserWhoIsRegistered", resourceCulture);
            }
        }
    }
}
