// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MY_WEB_APPLICATION.Controllers
{
    public partial class AccountController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Profile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Profile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult VerifyUserEmailAddress()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyUserEmailAddress);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Login()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string TermsAndConditions = "TermsAndConditions";
            public readonly string RegistrationDone = "RegistrationDone";
            public readonly string TerminateAccount = "TerminateAccount";
            public readonly string TerminateAccountConfirmed = "TerminateAccount";
            public readonly string Register = "Register";
            public readonly string SendAgainCellPhoneVerificationKey = "SendAgainCellPhoneVerificationKey";
            public readonly string SendAgainEmailAddressVerificationKey = "SendAgainEmailAddressVerificationKey";
            public readonly string ResetPassword = "ResetPassword";
            public readonly string Profile = "Profile";
            public readonly string VerifyUserEmailAddress = "VerifyUserEmailAddress";
            public readonly string VerifyUserCellPhoneNumber = "VerifyUserCellPhoneNumber";
            public readonly string Login = "Login";
            public readonly string Logout = "Logout";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string UpdateProfile = "UpdateProfile";
            public readonly string UploadAvatar = "UploadAvatar";
            public readonly string UploadAvatarConfirmed = "UploadAvatar";
            public readonly string DisplayUserAvatar = "DisplayUserAvatar";
            public readonly string UploadResume = "UploadResume";
            public readonly string UploadResumeConfirmed = "UploadResume";
            public readonly string DownloadResume = "DownloadResume";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string TermsAndConditions = "TermsAndConditions";
            public const string RegistrationDone = "RegistrationDone";
            public const string TerminateAccount = "TerminateAccount";
            public const string TerminateAccountConfirmed = "TerminateAccount";
            public const string Register = "Register";
            public const string SendAgainCellPhoneVerificationKey = "SendAgainCellPhoneVerificationKey";
            public const string SendAgainEmailAddressVerificationKey = "SendAgainEmailAddressVerificationKey";
            public const string ResetPassword = "ResetPassword";
            public const string Profile = "Profile";
            public const string VerifyUserEmailAddress = "VerifyUserEmailAddress";
            public const string VerifyUserCellPhoneNumber = "VerifyUserCellPhoneNumber";
            public const string Login = "Login";
            public const string Logout = "Logout";
            public const string ChangePassword = "ChangePassword";
            public const string UpdateProfile = "UpdateProfile";
            public const string UploadAvatar = "UploadAvatar";
            public const string UploadAvatarConfirmed = "UploadAvatar";
            public const string DisplayUserAvatar = "DisplayUserAvatar";
            public const string UploadResume = "UploadResume";
            public const string UploadResumeConfirmed = "UploadResume";
            public const string DownloadResume = "DownloadResume";
        }


        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_SendAgainEmailAddressVerificationKey s_params_SendAgainEmailAddressVerificationKey = new ActionParamsClass_SendAgainEmailAddressVerificationKey();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendAgainEmailAddressVerificationKey SendAgainEmailAddressVerificationKeyParams { get { return s_params_SendAgainEmailAddressVerificationKey; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendAgainEmailAddressVerificationKey
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Profile s_params_Profile = new ActionParamsClass_Profile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Profile ProfileParams { get { return s_params_Profile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Profile
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_VerifyUserEmailAddress s_params_VerifyUserEmailAddress = new ActionParamsClass_VerifyUserEmailAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VerifyUserEmailAddress VerifyUserEmailAddressParams { get { return s_params_VerifyUserEmailAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VerifyUserEmailAddress
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_VerifyUserCellPhoneNumber s_params_VerifyUserCellPhoneNumber = new ActionParamsClass_VerifyUserCellPhoneNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VerifyUserCellPhoneNumber VerifyUserCellPhoneNumberParams { get { return s_params_VerifyUserCellPhoneNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VerifyUserCellPhoneNumber
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_UpdateProfile s_params_UpdateProfile = new ActionParamsClass_UpdateProfile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateProfile UpdateProfileParams { get { return s_params_UpdateProfile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateProfile
        {
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_DisplayUserAvatar s_params_DisplayUserAvatar = new ActionParamsClass_DisplayUserAvatar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisplayUserAvatar DisplayUserAvatarParams { get { return s_params_DisplayUserAvatar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisplayUserAvatar
        {
            public readonly string id = "id";
            public readonly string width = "width";
            public readonly string height = "height";
        }
        static readonly ActionParamsClass_DownloadResume s_params_DownloadResume = new ActionParamsClass_DownloadResume();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadResume DownloadResumeParams { get { return s_params_DownloadResume; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadResume
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ChangePassword = "ChangePassword";
                public readonly string Index = "Index";
                public readonly string Login = "Login";
                public readonly string Profile = "Profile";
                public readonly string Register = "Register";
                public readonly string RegistrationDone = "RegistrationDone";
                public readonly string ResetPassword = "ResetPassword";
                public readonly string SendAgainCellPhoneVerificationKey = "SendAgainCellPhoneVerificationKey";
                public readonly string SendAgainEmailAddressVerificationKey = "SendAgainEmailAddressVerificationKey";
                public readonly string TerminateAccount = "TerminateAccount";
                public readonly string TermsAndConditions = "TermsAndConditions";
                public readonly string UpdateProfile = "UpdateProfile";
                public readonly string UploadAvatar = "UploadAvatar";
                public readonly string UploadResume = "UploadResume";
                public readonly string VerifyUserCellPhoneNumber = "VerifyUserCellPhoneNumber";
                public readonly string VerifyUserEmailAddress = "VerifyUserEmailAddress";
            }
            public readonly string ChangePassword = "~/Views/Account/ChangePassword.cshtml";
            public readonly string Index = "~/Views/Account/Index.cshtml";
            public readonly string Login = "~/Views/Account/Login.cshtml";
            public readonly string Profile = "~/Views/Account/Profile.cshtml";
            public readonly string Register = "~/Views/Account/Register.cshtml";
            public readonly string RegistrationDone = "~/Views/Account/RegistrationDone.cshtml";
            public readonly string ResetPassword = "~/Views/Account/ResetPassword.cshtml";
            public readonly string SendAgainCellPhoneVerificationKey = "~/Views/Account/SendAgainCellPhoneVerificationKey.cshtml";
            public readonly string SendAgainEmailAddressVerificationKey = "~/Views/Account/SendAgainEmailAddressVerificationKey.cshtml";
            public readonly string TerminateAccount = "~/Views/Account/TerminateAccount.cshtml";
            public readonly string TermsAndConditions = "~/Views/Account/TermsAndConditions.cshtml";
            public readonly string UpdateProfile = "~/Views/Account/UpdateProfile.cshtml";
            public readonly string UploadAvatar = "~/Views/Account/UploadAvatar.cshtml";
            public readonly string UploadResume = "~/Views/Account/UploadResume.cshtml";
            public readonly string VerifyUserCellPhoneNumber = "~/Views/Account/VerifyUserCellPhoneNumber.cshtml";
            public readonly string VerifyUserEmailAddress = "~/Views/Account/VerifyUserEmailAddress.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AccountController : MY_WEB_APPLICATION.Controllers.AccountController
    {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TermsAndConditionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TermsAndConditions()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TermsAndConditions);
            TermsAndConditionsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegistrationDoneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RegistrationDone()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegistrationDone);
            RegistrationDoneOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TerminateAccountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TerminateAccount()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TerminateAccount);
            TerminateAccountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TerminateAccountConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TerminateAccountConfirmed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TerminateAccountConfirmed);
            TerminateAccountConfirmedOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            RegisterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.RegisterViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register(ViewModels.Account.RegisterViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RegisterOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void SendAgainCellPhoneVerificationKeyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendAgainCellPhoneVerificationKey()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendAgainCellPhoneVerificationKey);
            SendAgainCellPhoneVerificationKeyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SendAgainEmailAddressVerificationKeyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendAgainEmailAddressVerificationKey()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendAgainEmailAddressVerificationKey);
            SendAgainEmailAddressVerificationKeyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SendAgainEmailAddressVerificationKeyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.SendAgainEmailAddressVerificationKeyViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendAgainEmailAddressVerificationKey(ViewModels.Account.SendAgainEmailAddressVerificationKeyViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendAgainEmailAddressVerificationKey);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SendAgainEmailAddressVerificationKeyOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ResetPasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.ResetPasswordViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetPassword(ViewModels.Account.ResetPasswordViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ResetPasswordOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Profile(System.Guid? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Profile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ProfileOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void VerifyUserEmailAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult VerifyUserEmailAddress(System.Guid? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyUserEmailAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            VerifyUserEmailAddressOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void VerifyUserCellPhoneNumberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult VerifyUserCellPhoneNumber()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyUserCellPhoneNumber);
            VerifyUserCellPhoneNumberOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void VerifyUserCellPhoneNumberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.VerifyUserCellPhoneNumberViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult VerifyUserCellPhoneNumber(ViewModels.Account.VerifyUserCellPhoneNumberViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyUserCellPhoneNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            VerifyUserCellPhoneNumberOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.LoginViewModel viewModel, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(ViewModels.Account.LoginViewModel viewModel, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, viewModel, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ChangePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModels.Account.ChangePasswordViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword(ViewModels.Account.ChangePasswordViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ChangePasswordOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateProfile()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            UpdateProfileOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Models.User user);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateProfile(Models.User user)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            UpdateProfileOverride(callInfo, user);
            return callInfo;
        }

        [NonAction]
        partial void UploadAvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadAvatar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAvatar);
            UploadAvatarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadAvatarConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadAvatarConfirmed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAvatarConfirmed);
            UploadAvatarConfirmedOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisplayUserAvatarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id, int? width, int? height);

        [NonAction]
        public override System.Web.Mvc.ActionResult DisplayUserAvatar(System.Guid? id, int? width, int? height)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisplayUserAvatar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "width", width);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "height", height);
            DisplayUserAvatarOverride(callInfo, id, width, height);
            return callInfo;
        }

        [NonAction]
        partial void UploadResumeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadResume()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadResume);
            UploadResumeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadResumeConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadResumeConfirmed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadResumeConfirmed);
            UploadResumeConfirmedOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DownloadResumeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadResume(System.Guid? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadResume);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadResumeOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
