// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Partial_CaptchaImage = "_Partial_CaptchaImage";
                public readonly string _Partial_ChangeCulture = "_Partial_ChangeCulture";
                public readonly string _Partial_DisplayEntityDetails = "_Partial_DisplayEntityDetails";
                public readonly string _Partial_DisplayLocalizedPageContent = "_Partial_DisplayLocalizedPageContent";
                public readonly string _Partial_DisplayMenu = "_Partial_DisplayMenu";
                public readonly string _Partial_DisplayPageMessages = "_Partial_DisplayPageMessages";
                public readonly string _Partial_DisplayPost = "_Partial_DisplayPost";
                public readonly string _Partial_DisplayPostCategorySubMenu = "_Partial_DisplayPostCategorySubMenu";
                public readonly string _Partial_DisplayPosts = "_Partial_DisplayPosts";
                public readonly string _Partial_DisplayPostsOnHomePage = "_Partial_DisplayPostsOnHomePage";
                public readonly string _Partial_DisplayPostTags = "_Partial_DisplayPostTags";
                public readonly string _Partial_DisplaySupervisorDashboard = "_Partial_DisplaySupervisorDashboard";
                public readonly string _Partial_DisplayUserDashboard = "_Partial_DisplayUserDashboard";
                public readonly string _Partial_SelectProjectActions = "_Partial_SelectProjectActions";
                public readonly string _Partial_TinyMce = "_Partial_TinyMce";
                public readonly string _Partial_UserLoginStatus = "_Partial_UserLoginStatus";
            }
            public readonly string _Partial_CaptchaImage = "~/Views/Shared/_Partial_CaptchaImage.cshtml";
            public readonly string _Partial_ChangeCulture = "~/Views/Shared/_Partial_ChangeCulture.cshtml";
            public readonly string _Partial_DisplayEntityDetails = "~/Views/Shared/_Partial_DisplayEntityDetails.cshtml";
            public readonly string _Partial_DisplayLocalizedPageContent = "~/Views/Shared/_Partial_DisplayLocalizedPageContent.cshtml";
            public readonly string _Partial_DisplayMenu = "~/Views/Shared/_Partial_DisplayMenu.cshtml";
            public readonly string _Partial_DisplayPageMessages = "~/Views/Shared/_Partial_DisplayPageMessages.cshtml";
            public readonly string _Partial_DisplayPost = "~/Views/Shared/_Partial_DisplayPost.cshtml";
            public readonly string _Partial_DisplayPostCategorySubMenu = "~/Views/Shared/_Partial_DisplayPostCategorySubMenu.cshtml";
            public readonly string _Partial_DisplayPosts = "~/Views/Shared/_Partial_DisplayPosts.cshtml";
            public readonly string _Partial_DisplayPostsOnHomePage = "~/Views/Shared/_Partial_DisplayPostsOnHomePage.cshtml";
            public readonly string _Partial_DisplayPostTags = "~/Views/Shared/_Partial_DisplayPostTags.cshtml";
            public readonly string _Partial_DisplaySupervisorDashboard = "~/Views/Shared/_Partial_DisplaySupervisorDashboard.cshtml";
            public readonly string _Partial_DisplayUserDashboard = "~/Views/Shared/_Partial_DisplayUserDashboard.cshtml";
            public readonly string _Partial_SelectProjectActions = "~/Views/Shared/_Partial_SelectProjectActions.cshtml";
            public readonly string _Partial_TinyMce = "~/Views/Shared/_Partial_TinyMce.cshtml";
            public readonly string _Partial_UserLoginStatus = "~/Views/Shared/_Partial_UserLoginStatus.cshtml";
            static readonly __LayoutsClass s__Layouts = new __LayoutsClass();
            public __LayoutsClass _Layouts { get { return s__Layouts; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class __LayoutsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                }
                static readonly _default_en_USClass s_default_en_US = new _default_en_USClass();
                public _default_en_USClass default_en_US { get { return s_default_en_US; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _default_en_USClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Site = "_Site";
                    }
                    public readonly string _Site = "~/Views/Shared/_Layouts/default.en-US/_Site.cshtml";
                }
                static readonly _default_fa_IRClass s_default_fa_IR = new _default_fa_IRClass();
                public _default_fa_IRClass default_fa_IR { get { return s_default_fa_IR; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _default_fa_IRClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Site = "_Site";
                    }
                    public readonly string _Site = "~/Views/Shared/_Layouts/default.fa-IR/_Site.cshtml";
                }
                static readonly _home_fa_IRClass s_home_fa_IR = new _home_fa_IRClass();
                public _home_fa_IRClass home_fa_IR { get { return s_home_fa_IR; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _home_fa_IRClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Site = "_Site";
                    }
                    public readonly string _Site = "~/Views/Shared/_Layouts/home.fa-IR/_Site.cshtml";
                }
                static readonly _rss_post_fa_IRClass s_rss_post_fa_IR = new _rss_post_fa_IRClass();
                public _rss_post_fa_IRClass rss_post_fa_IR { get { return s_rss_post_fa_IR; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _rss_post_fa_IRClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Site = "_Site";
                    }
                    public readonly string _Site = "~/Views/Shared/_Layouts/rss_post.fa-IR/_Site.cshtml";
                }
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Boolean = "Boolean";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
