//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Captions {
        
        /// <summary>
        ///   Looks up a localized string similar to: After
        /// </summary>
        public static string After([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.After;
            }
            return global::Resources.Captions.ResourceManager.GetString("After", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Before
        /// </summary>
        public static string Before([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.Before;
            }
            return global::Resources.Captions.ResourceManager.GetString("Before", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Date
        /// </summary>
        public static string Date([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.Date;
            }
            return global::Resources.Captions.ResourceManager.GetString("Date", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Downloaded Files
        /// </summary>
        public static string DownloadedFiles([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.DownloadedFiles;
            }
            return global::Resources.Captions.ResourceManager.GetString("DownloadedFiles", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Loading...
        /// </summary>
        public static string Loading([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.Loading;
            }
            return global::Resources.Captions.ResourceManager.GetString("Loading", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Please Wait...
        /// </summary>
        public static string PleaseWait([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.PleaseWait;
            }
            return global::Resources.Captions.ResourceManager.GetString("PleaseWait", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Select An Item...
        /// </summary>
        public static string SelectAnItem([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.SelectAnItem;
            }
            return global::Resources.Captions.ResourceManager.GetString("SelectAnItem", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Version
        /// </summary>
        public static string Version([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Captions.Version;
            }
            return global::Resources.Captions.ResourceManager.GetString("Version", resourceCulture);
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class CaptionsKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: After
        /// </summary>
        public const string After = "After";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Before
        /// </summary>
        public const string Before = "Before";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Date
        /// </summary>
        public const string Date = "Date";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Downloaded Files
        /// </summary>
        public const string DownloadedFiles = "DownloadedFiles";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Loading...
        /// </summary>
        public const string Loading = "Loading";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Please Wait...
        /// </summary>
        public const string PleaseWait = "PleaseWait";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Select An Item...
        /// </summary>
        public const string SelectAnItem = "SelectAnItem";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Version
        /// </summary>
        public const string Version = "Version";
    }
}
