//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از بانک اطلاعاتی با موفقيت فايل پشتيبان گرفته شد. .
        /// </summary>
        public static string DatabaseBackup {
            get {
                return ResourceManager.GetString("DatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری و/يا گذرواژه صحيح نمی باشد! لطفا مجددا سعی کنيد.
        /// </summary>
        public static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه تا اين لحظه، نشانی پست الکترونيکی شما تاييد نشده است! لطفا برای تاييد آن، به صندوق پست الکترونيکی خود مراجعه نماييد..
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه شما قادر به ورود به پايگاه نمی‌باشيد! لطفا با مسوولين پايگاه تماس حاصل فرماييد..
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صفحه تکراری است! لطفا از نام ديگری استفاده نماييد..
        /// </summary>
        public static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است! لطفا از {0} ديگری استفاده نماييد..
        /// </summary>
        public static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} تکراری است! لطفا از {0} ديگری استفاده نماييد..
        /// </summary>
        public static string Error006 {
            get {
                return ResourceManager.GetString("Error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} صفحه از اين قالب استفاده می کند! لذا شما قادر به حذف آن نمی‌باشيد..
        /// </summary>
        public static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه گذرواژه جاری را به درستی وارد نکرده ايد!.
        /// </summary>
        public static string Error008 {
            get {
                return ResourceManager.GetString("Error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جديد شما با موفقيت ثبت گرديد. .
        /// </summary>
        public static string Information001 {
            get {
                return ResourceManager.GetString("Information001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شما با موفقيت ثبت گرديد..
        /// </summary>
        public static string Information002 {
            get {
                return ResourceManager.GetString("Information002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات به‌روزرسانی اطلاعات زيرسيستم‌ها، بخش‌ها و فعاليت‌ها با موفقيت انجام گرديد..
        /// </summary>
        public static string Information003 {
            get {
                return ResourceManager.GetString("Information003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس شما با موفقيت ارسال گرديد.
        /// </summary>
        public static string Information004 {
            get {
                return ResourceManager.GetString("Information004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزومه شما با موفقيت ارسال گرديد.
        /// </summary>
        public static string Information005 {
            get {
                return ResourceManager.GetString("Information005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فايل مربوطه در مدت {0} با موفقيت ذخيره گرديد..
        /// </summary>
        public static string Information006 {
            get {
                return ResourceManager.GetString("Information006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Question001 {
            get {
                return ResourceManager.GetString("Question001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information saved successfully..
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته‌ای صورت گرفته است! لطفا با مسوولين پايگاه تماس حاصل فرماييد..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
