//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModels.Resources.Areas.Administrator.WebDownloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DownloadViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownloadViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel", typeof(DownloadViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLoad And Save To File Duration.
        /// </summary>
        public static string DownLoadAndSaveToFileDuration {
            get {
                return ResourceManager.GetString("DownLoadAndSaveToFileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush.
        /// </summary>
        public static string Flush {
            get {
                return ResourceManager.GetString("Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush Length.
        /// </summary>
        public static string FlushLength {
            get {
                return ResourceManager.GetString("FlushLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Size.
        /// </summary>
        public static string PocketSize {
            get {
                return ResourceManager.GetString("PocketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File Url.
        /// </summary>
        public static string SourceFileUrl {
            get {
                return ResourceManager.GetString("SourceFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Timeout.
        /// </summary>
        public static string SourceTimeout {
            get {
                return ResourceManager.GetString("SourceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File Name.
        /// </summary>
        public static string TargetFileName {
            get {
                return ResourceManager.GetString("TargetFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Timeout.
        /// </summary>
        public static string TargetTimeout {
            get {
                return ResourceManager.GetString("TargetTimeout", resourceCulture);
            }
        }
    }
}
