//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace ViewModels.Resources.Areas.Administrator.WebDownloader.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DownloadViewModel {
        
        /// <summary>
        ///   Looks up a localized string similar to: DownLoad And Save To File Duration
        /// </summary>
        public static string DownLoadAndSaveToFileDuration([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.DownLoadAndSaveToFileDuration;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("DownLoadAndSaveToFileDuration", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Flush
        /// </summary>
        public static string Flush([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.Flush;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("Flush", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Flush Length
        /// </summary>
        public static string FlushLength([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.FlushLength;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("FlushLength", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Pocket Size
        /// </summary>
        public static string PocketSize([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.PocketSize;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("PocketSize", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Source File Url
        /// </summary>
        public static string SourceFileUrl([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.SourceFileUrl;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("SourceFileUrl", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Source Timeout
        /// </summary>
        public static string SourceTimeout([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.SourceTimeout;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("SourceTimeout", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Target File Name
        /// </summary>
        public static string TargetFileName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.TargetFileName;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("TargetFileName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Target Timeout
        /// </summary>
        public static string TargetTimeout([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.TargetTimeout;
            }
            return global::ViewModels.Resources.Areas.Administrator.WebDownloader.DownloadViewModel.ResourceManager.GetString("TargetTimeout", resourceCulture);
        }
    }
}
namespace ViewModels.Resources.Areas.Administrator.WebDownloader.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DownloadViewModelKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: DownLoad And Save To File Duration
        /// </summary>
        public const string DownLoadAndSaveToFileDuration = "DownLoadAndSaveToFileDuration";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Flush
        /// </summary>
        public const string Flush = "Flush";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Flush Length
        /// </summary>
        public const string FlushLength = "FlushLength";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Pocket Size
        /// </summary>
        public const string PocketSize = "PocketSize";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Source File Url
        /// </summary>
        public const string SourceFileUrl = "SourceFileUrl";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Source Timeout
        /// </summary>
        public const string SourceTimeout = "SourceTimeout";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Target File Name
        /// </summary>
        public const string TargetFileName = "TargetFileName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Target Timeout
        /// </summary>
        public const string TargetTimeout = "TargetTimeout";
    }
}
